### ISSUE TITLE
iso menu input fields disappear

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/ShapeWorksStudio#42]
in the analysis stage of the shapeworks gui, when trying to adjust the isosurfacing value, the fields disappear when you click on them, making it extremely difficult to change them.  It appears to be some kind of pop-up menu or tooltip that is white and empty, so it blanks out that part of the screen.

**Comment by brigb123** [comment]
@jessdtate Can you post your machine hardware and OS here? I don't see this problem on any of my machines. I want to put a note for specific machines.

**Comment by jessdtate** [comment]
OS X 10.8 intel 2 core duo, 8 GB ram.  NVIDIA Geforce 9400M graphics card.  I have QT 4.8.5, but I suppose since it is precompiled it would be whatever you built it with.

**Comment by jessdtate** [comment]
I haven't been able to reproduce the bug since yesterday, even on the same machine.

**Comment by brigb123** [comment]
Ok, I'm going to close this for now. I'll re-open if we see it on IBBM Participant machines.
