### ISSUE TITLE
can't deselect particles

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorksStudio#45]
when hovering on a particle and pressing 1, there is no way to return back to the original display of the correspondence model, even if I ran the optimization again

**Comment by brigb123** [comment]
This is done by pressing 1 or 2 again while NOT hovering over a point. (black space or whatever.) 

Since the selection of points is not documented, neither is the de-selection. If you want this documented, you can add it as an issue request.
