### ISSUE TITLE
project saved without parameters

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorksStudio#48]
when saving a studio project then loading that project, there is no way we can retrieve the grooming or optimization parameters that were used to construct such a project

**Comment by brigb123** [comment]
groom params done here 2954edb1e1df5301724c965279167beff8f5fbdc

need to include optimize params

**Comment by brigb123** [comment]
done here 1cfb88f956740b2f0c3dff397ef94d18d9aa2427
