### ISSUE TITLE
Need to save a parameter XML for a command line binary

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorksStudio#49]
Studio has the option to save groom and optimize xml parameter files, yet there is no obvious option to load a previously save xml file

**Comment by brigb123** [comment]
Going to amend this issue. Studio can save/load default parameters associated with a project. An exported XML will be expected for use by a command line binary to run on more images.

**Comment by brigb123** [comment]
Also need to create that binary...
