### ISSUE TITLE
Crash on Windows 8.1 during Optimize

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/ShapeWorksStudio#52]
ShapeworksStudio crashes during the optimize step on Windows 8.1 64-bit. Tested using both the torus and the mickey sample data and using the parameters in the tutorial.

![shapeworksstdio](https://cloud.githubusercontent.com/assets/1399377/8607240/e081c59a-264e-11e5-8f30-3622013b441b.PNG)

**Comment by brigb123** [comment]
@aylakhan Is there a machine I can test this on? the cibc test machines all appear to run 8.0, and I was successful in running studio on both.

**Comment by aylakhan** [comment]
In the CIBC lab - info in email.

**Comment by brigb123** [comment]
This looks like a path problem when spaces are present. Still a bug, but the workaround is to put data in paths with no spaces.

**Comment by brigb123** [comment]
deferred to #54
