### ISSUE TITLE
Processing large datasets: I can't import 1000 images into studio. 

### ISSUE THREAD

**Issue by prasanna86** [SCIInstitute/ShapeWorksStudio#58]
I tried importing 1016 mha images into the ui. For some reason it only imports 885 images. I'm not sure whether this is a hard set value or is this number computed based on minimum window size allotted for each image that it can't go beyond 885. Since I can't load in all my data, I'm not able to process all of them together.

**Comment by brigb123** [comment]
At the moment, the UI is not meant to visualize many samples. Below 60 is the use-case. The Studio will be a customizing tool to help a user find the parameters needed for a large batch process to run on the command line.
