### ISSUE TITLE
Setting output directory

### ISSUE THREAD

**Issue by prasanna86** [SCIInstitute/ShapeWorksStudio#60]
Currently processed files (groom, optimize) store output files in the same folder. I realize if I have to organize them into a different folder, I would need to export xml, and edit the xml to change the path of all output files. If there was a way to specify alternate output directory locations as part of the ui, organization becomes easier and more efficient.

**Comment by brigb123** [comment]
done here b2ad81f419f2ffbe24b44450b8e4122f9aab037e
