### ISSUE TITLE
Doubled button in OS X fullscreen mode

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/ShapeWorksStudio#72]
Seen on OS X 10.10.5 in fullscreen mode:

<img width="662" alt="shapeworks_toolbar" src="https://cloud.githubusercontent.com/assets/1399377/14921779/3342e3ce-0df1-11e6-8dd0-1491c8ad18a7.png">

**Comment by brigb123** [comment]
bug noted in README here 39d43532a62b0fc52c0775ade793b67a4c2fb5af
