### ISSUE TITLE
Optimize Step Failed With Image Based Geometry (Hearts)

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/ShapeWorksStudio#75]
Geometries are not being seeded with correspondence points after the optimization set.  This was true for: 1) Single Label Heart Geometries with holes (ventricles) filled, 2) Single Label Heart Geometries with holes (ventricles) unfilled, and 3) Two labeled geometries (heart and blood)
[SingleLabelHearts.zip](https://github.com/SCIInstitute/ShapeWorksStudio/files/242879/SingleLabelHearts.zip)
[DoubleLabelHearts.zip](https://github.com/SCIInstitute/ShapeWorksStudio/files/242883/DoubleLabelHearts.zip)

**Comment by wgood** [comment]
Using the same geometries I am able to Groom the geometries but it fails on the optimization giving the error ----"Error: std::exception" with no delay.

**Comment by brigb123** [comment]
Data isn't fit for shapeworks. Spacings are different, and there are too many convex holes for optimize to understand correctly. A good dataset for SW would have identical sizes, spacings, and be the outer shell of the hearts.
