### ISSUE TITLE
FastMarching Option Not Working

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/ShapeWorksStudio#83]
Using FastMarching option in the Grooming section produces errant surface files to optimize:

The output after FastMarching looks like this:
![using fastmarching](https://cloud.githubusercontent.com/assets/3486194/16019655/3b224cee-3167-11e6-807c-d26a19f87195.png)

Without FastMarching it looks like this:
![not using fastmarching](https://cloud.githubusercontent.com/assets/3486194/16019669/4f5d35ca-3167-11e6-80eb-dd530956296c.png)

**Comment by zaracay** [comment]
Try using the old FastMarching code

**Comment by brigb123** [comment]
There might be special setting for optimize to handle the distance maps properly. Will work with Shireen to figure this out.

**Comment by brigb123** [comment]
There was a bug not resetting reconstruction on re-runs. c514907f5e50745b2141d5c8b52843a632aae00e closes this
